//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GameRuntime
{
	private static GameUtils.Shaker m_camShaker = new GameUtils.Shaker(Vector3.zero, 0, 0, 0);
	private static Vector3 m_camOrgPos;

	public static void Init() {
		ResManager.Init ();
		GameObjectPool.Init();

		floor = GameObject.Find("FloorObject").GetComponent<Floor>();
		curLevel = new LevelRuntime();
		curLevel.Init();
		labelScore = GameObject.Find("Label:Score").GetComponent<UILabel>();
		labelScore.text = "Score: 0";
		labelGold = GameObject.Find("Label:Gold").GetComponent<UILabel>();

		Time.maximumDeltaTime = 0.03f;
		m_camOrgPos = Camera.main.transform.position;
	}

	public static void Update() {
		float dt = Time.smoothDeltaTime;
		GameObjectPool.Update(dt);
		m_camShaker.Update(dt);
		curLevel.Update(dt);	
		Vector3 camPos = m_camOrgPos;
		camPos.z = curLevel.HeadZ - 2;
		camPos += m_camShaker.GetOffset();
		Camera.main.transform.position = camPos;
		labelScore.text = "Score: " + ((int)(curLevel.HeadZ)).ToString();
		//float fTurn = Mathf.Sin(Time.time * 0.1f) * 5;
		float fTurn = Mathf.PerlinNoise(0, camPos.z * 0.002f) * 24 - 12;
		ResManager.m_gridMaterial[ResManager.GRID_FLOOR].SetFloat("_TurnX", fTurn);
		ResManager.m_gridMaterial[ResManager.GRID_HEAD].SetFloat("_TurnX", fTurn);
		ResManager.m_gridMaterial[ResManager.GRID_BLOCK_SIDE_LEFT].SetFloat("_TurnX", fTurn);
		ResManager.m_decalMaterial[ResManager.DECAL_HIT].SetFloat("_TurnX", fTurn);
		turnX = fTurn;
	}

	public static void ShakeCamera(Vector3 dir, float time, float amount, float rate)
	{
		m_camShaker = new GameUtils.Shaker(dir, time, amount, rate);
	}

	public static LevelRuntime curLevel;
	public static float turnX = 0;
	public static Floor floor;
	public static UILabel labelScore;
	public static UILabel labelGold;
	public static System.Random random = new System.Random();

}

